config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users 
  resources :collections 

  resources :groups do 
    resources :comments
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :group
  belongs_to :user 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :group 

  validates :author, presence: true 

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :collections
  has_many :comments 
  has_many :users, :through => :collections

  validates :topic, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :address, presence: true
  validates :city, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :collections 
  has_many :groups, :through => :collections

  validates :email, presence: true
  validates :username, presence: true

  geocoded_by :address
  after_validation :geocode

  def has_group_access?(group_id)
    Collection.find_by_group_id_and_user_id(group_id, self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, 
    :password_confirmation, :username, :address, :city, :state) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, 
   :password_confirmation, :current_password, :username, :address, :city, :state) }
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def index
    @collections = Collection.all
  end 

  def show
    @collection = Collection.find(params[:id])
  end

  def new 
    @collection = Collection.new 
  end 

  def create 
  end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index 
    @group = Group.find(params[:group_id])
  end

  def new 
    @group = Group.find(params[:group_id])
    @comment = @group.comments.new
  end 

  def create
    @group = Group.find(params[:group_id])
    @comment = @group.comments.new(comment_params)
    if @comment.save 
      redirect_to @group 
    else 
      render 'new'
    end 
  end 

  def edit 
    @group = Group.find(params[:group_id])
    @comment = @group.comments.find(params[:id])
  end

  def update
    @group = Group.find(params[:group_id])
    @comment = @group.comments.find(params[:id])
    if @comment.update_attributes(comment_params)
      #handles an update
      redirect_to @group, notice: "Comment was successfully created!"
    else 
      render action: :edit
    end 
  end 

  def destroy
    @group = Group.find(params[:group_id])
    @comment = @group.comments.find(params[:id])
    if @comment.destroy
      flash[:success] = "Comment Destroyed"
    else 
      flash[:error] = "Comment could not be deleted"
    end 
    redirect_to @group
  end 

  private 

    def comment_params 
      params.require(:comment).permit(:author, :comment, :user_id, :group_id)
    end 

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  include GroupsHelper

  def index 
    @groups = Group.includes(:comments)
    @group_count = 0

    @nearby_groups = []

    @groups.each do |group|
      if nearby(group.longitude, group.latitude, current_user.longitude, current_user.latitude)
        @group_count += 1
        @nearby_groups.push(group)
      end 
    end 
  end

  def show
    @group = Group.find(params[:id])
  end 

  def new 
    @group = Group.new 
    @collections = Collection.all
  end 

  def create
    @group = Group.new(group_params)
    if @group.save 
      redirect_to @group 
    else 
      render 'new'
    end
  end 

  def edit 
    @group = Group.find(params[:id])
  end 

  def update 
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      #Hanles an update
      redirect_to @group
    else 
      'edit'
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    redirect_to groups_url
  end

  private

    def group_params
      params.require(:group).permit(:topic, :user_id, :description, :address, :city, :state) 
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper

  def nearby(longitude1, latitude1, longitude2, latitude2)
    if (longitude1-longitude2).abs <= 0.01 && (latitude1-latitude2).abs <= 0.01
      return true
    else
      return false
    end 
  end 
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/collections/index.html.erb
<div class="container main">
  <h1>Collections</h1>
  <%= link_to "New", new_collection_path, class: "ui inverted black button active" %>
  <hr>
  <% @collections.each do |collection| %>
      <h1>Collection name: <%= collection.name %><h1>
      <p>Groups in Collection: <%= collection.group.topic %></p>
      <p>Members in Collection: <%= collection.user.username %></p>
      <%= link_to "Show", collection_path(collection) %>
      <hr>
  <% end %>
</div>

app/views/collections/new.html.erb
<div class="container main">
  <h1>Add a New Collection</h1>
</div>

app/views/collections/show.html.erb
<div class="container main">
  <h1><%= @collection.name %><h1>
  <p>Group: <%= @collection.group.topic %></p>
  <p>Members: <%= @collection.user.username %></p>
</div>

app/views/comments/edit.html.erb
<div class="container main">
  <h1>Edit Comment</h1>

  <div class="text-center">
    <% if @comment.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@comment.errors.count, "error") %> Stopped this comment from saving</h2>
        <ul>
          <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <%= form_for [@group, @comment] do |form| %>

    <div class="form-group">
      <%= form.label :author %>
      <%= form.text_field :author, class: "form-control", placeholder: "Title" %>
    </div>

    <div class="form-group">
      <%= form.label :comment %>
      <%= form.text_field :comment, class: "form-control", placeholder: "What is on your mind?" %>
    </div>

    <div class="hide">
      <%= form.number_field :user_id, value: current_user.id %>
    </div>

    <%= form.submit "Submit", class: "btn btn-info" %>

  <% end %>
</div>

app/views/comments/new.html.erb
<div class="container main">
  <h1>New Comment</h1>

  <div class="text-center">
    <% if @comment.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@comment.errors.count, "error") %> Stopped this comment from saving</h2>
        <ul>
          <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <%= form_for [@group, @comment] do |form| %>

    <div class="form-group">
      <%= form.label :author %>
      <%= form.text_field :author, class: "form-control", placeholder: "Title" %>
    </div>

    <div class="form-group">
      <%= form.label :comment %>
      <%= form.text_field :comment, class: "form-control", placeholder: "What is on your mind?" %>
    </div>

    <div class="hide">
      <%= form.number_field :user_id, value: current_user.id %>
    </div>

    <%= form.submit "Submit", class: "btn btn-info" %>

  <% end %>
</div>

app/views/groups/_form.html.erb
<div class="container">

  <div class="text-center">
    <% if @group.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@group.errors.count, "error") %> Stopped this Group from saving</h2>
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :topic %>
    <%= form.text_field :topic, autofocus: true, class: "form-control", placeholder: "Group Topic" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control", placeholder: "Group Description" %>
  </div>

  <div class="form-group">
    <%= form.label :city %><br />
    <%= form.text_field :city, class: "form-control", placeholder: "Enter city" %>
  </div>

  <div class="form-group">
    <%= form.label :state %><br />
    <%= form.text_field :state, class: "form-control", placeholder: "Enter state" %>
  </div>

  <div class="form-group">
    <%= form.label :address %><br />
    <%= form.text_field :address, class: "form-control", placeholder: "Enter address" %>
  </div>

  <div class="hide">
    <%= form.number_field :user_id, value: current_user.id %>
  </div>



  <%= form.submit "Submit", class: "ui button" %>

</div>

app/views/groups/edit.html.erb
<div class="container main">
  <h1>Edit Group<h1>

    <%= form_for (@group) do |form| %>
      <%= render partial: form %>
    <% end %>
</div>

app/views/groups/index.html.erb
<div class="ui raised very padded text container segment main">
  <h1 class="ui header edit-fix">Listing Groups Near Your Location</h1>
  <div class="edit-fix">
    <%= link_to "New Group", new_group_path, class: "ui inverted green button active" %>
  </div>

  <% @nearby_groups.each do |group| %>
    <h1><%= group.topic %></h1>
    <p><%= group.description %></p>
    <%# if current_user.id == group.user.id %>
    <%#if current_user and current_user.has_group_access?(@group.id) %>
    <% if current_user and current_user.id == group.user_id %>
      <%= link_to "Edit", edit_group_path(group), class: "ui black button" %>
      <%= link_to "Delete", group_path(group), method: :delete, data: { confirm: "Are you Sure?"},
        class: "ui inverted red button " %>
    <% end %>
    <%= link_to "show", group_path(group), class: "ui inverted blue button" %>
  <% end %>
</div>

app/views/groups/new.html.erb
<div class="container main">
  <h1 class="edit-fix">New Group<h1>

    <%= form_for (@group) do |form| %>
      <%= render partial: form %>
    <% end %>
</div>

app/views/groups/show.html.erb
<div class="container main">
  <h1>The <%= @group.topic %> Group!</h1>
  <p>Description: <em><%= @group.description %></em></p>
  <p>Group Address: <em><%= @group.address %></em></p>
  <p>Group City: <em><%= @group.city %></em></p>
  <p>Group State: <em><%= @group.state %></em></p>
  <% if current_user and current_user.id == @group.user_id %>
    <%= link_to "Edit", edit_group_path(), class: "ui black button" %>
    <%= link_to "Delete", group_path(), method: :delete, data: { confirm: "Are you Sure?"},
        class: "ui inverted red button " %>
  <% end %>
</div>


<div class="container comment_container">
<hr>
    <h2><em>Comments:</em></h2>
  <% @group.comments.each do |comment| %>
    <p><%= comment.author %> says:</p>
    <p><%= comment.comment %></p>
    <% if current_user and current_user.id == comment.user_id %>
      <p><%= link_to "Edit", edit_group_comment_path(@group, comment), class: "ui grey button" %>
      <%= link_to "Delete", group_comment_path(@group, comment), method: :delete, data: { confirm: "Are you sure?"}, class: "ui inverted red button" %></p>
    <% end %>
    <hr>
  <% end %>
  <%= link_to "New", new_group_comment_path(@group), class: "ui inverted black button active" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meetup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="ui fixed inverted menu">
  <div class="ui container">
    <div class="header item"><i class="users icon"></i>Come Together</div>
      <li class="item"><%= link_to "Home", root_path %></li>
      <li class="item"><%= link_to "Groups", groups_path %></li>
      <% if user_signed_in? %>
        <li class="item"><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li class="item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
    </div>
  </div>
</div>

<% flash.each do |type, message| %>
  <div class="alert flash <%= type %>">
    <%= message %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container main">
  <div class="jumbotron">
    <section class="banner" > 
      <div class="inner">
        <h3 class="banner-heading">Come Together</h3>
          <hr>
        <p class="inner_font">Like Minded People Meeting</P>
          <p>Right Now</p>
      </div>
    </section>
</div>
</div>

<div class="container segment_center">
  <h1>Imagine all the People...Coming Together</h1>
</div>

<div class="container segment_info">
  <div class="ui horizontal segments">
    <div class="ui black segment segment_center font">
      <h1>About</h1>
      <p>Imagine a world where you actually speak to you neighboor...</p>
      <p>Imagine a world where you know the people in your neighborhood</p>
      <p>Come Together is about bringing groups of people together</p>
      <p>We believe that people should connect with each other...in their neighborhoods.</p>
    </div>
    <div class="ui black segment segment_center font">
      <h1>How this Works</h1>
      <p>The site will take your address that you entered when you created your profile.</p>
      <p>It will then show you which groups are closest to your location.</p>
      <p>If there are no groups in your neighborhood then nothing will appear on the groups page.</p>
      <p>Thus, you should create a group for others to come together!</p>
      <p>Once the group has been created you can post messages in the group.</p>
    </div>
    <div class="ui black segment segment_center font">
      <h1>Groups</h1>
      <p>Once you join feel free to look at the groups that one can belong to.</p>
      <p>The groups are based on the location of your home.</p>
      <p>Thus, if your neighborhood has a group it will appear</p>
      <p>You can also create new groups for your neighborhood.</p>
    </div>
  </div>
</div>